### ISSUE TITLE
А зачем нам именно для 2n ставить такие отступы, почему нельзя для всех?

### ISSUE THREAD

**Issue by didolf** [loginsan/task-1.3#2]
https://github.com/loginsan/task-1.3/blob/3534df2609fa07622a9cc8f82d688de44e65dc7f/styles/styles.css#L507

**Comment by didolf** [comment]
Воспользуйся лучше grid'ом с автозаполнением

**Comment by loginsan** [comment]
> Воспользуйся лучше grid'ом с автозаполнением
grid'ами вообще очень просто получилось (олдскул за хардкор =)
